Start-Sleep ((get-date "10:00am")-(get-date)).TotalSeconds;
Start-Process cmd -Argument "/c tree";
Start-Process cmd -Argument "/c tree";
Start-Sleep -Seconds 1; 
Start-Process cmd -Argument "/c tree";
Start-Process cmd -Argument "/c ping 8.8.8.8  /n 3 ";
Start-Sleep -Seconds 2;
Add-Type -AssemblyName System.speech;
$speak=New-Object System.Speech.Synthesis.SpeechSynthesizer;
$speak.Speak('Laters lads. WC prid.  Bob mason over Ray chung any day. #free ali.');
start "https://www.youtube.com/watch?v=apbomWp3_cw";
Start-Sleep -Seconds 4;
$wshell = New-Object -ComObject wscript.shell;
$wshell.SendKeys(' ');
Start-Sleep -Seconds 3;
start microsoft.windows.camera:;
Start-Sleep -Seconds 1;
$wshell.SendKeys(' ');
Start-Sleep -Seconds 1;
$speak.Speak('caught lackin');
